apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJiMjF5Wld0bGNqcG5hSEJmTkcxeVRYRklTR1ZMUmtvemFXOWtWakZDYjAxdE5HNTZiR1JoTmtrNE1GRm1la1Y1In19fQ==
type: kubernetes.io/dockerconfigjson
